repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=16384']
        exclude: "^data/"
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        entry: bash -c 'cargo fmt --all'
        language: system
        fail_fast: true
# -   repo: local
#     hooks:
#       - id: next-eslint
#         name: next-eslint
#         entry: bash -c 'npm run lint'
#         language: system
#         fail_fast: true
-   repo: local
    hooks:
      - id: cargo-clippy
        name: cargo-clippy
        entry: bash -c 'cargo clippy --fix --allow-staged --features=pimoroni-display-hat-mini,bmp,text,transitions -- -D warnings'
        language: system
        fail_fast: true
# -   repo: local
#     hooks:
#       - id: cargo-test
#         name: cargo-test
#         entry: bash -c 'cargo test'
#         language: system
